#!/bin/bash

rm /home/santoku/Workspace/Proj201404/dot2smali/input/smali/mistore_* -rf

for i in {1..640}
do
  ./instrument -c -f ./appsets/GooglePlay/googleplay_${i}.apk
done

java -jar ./log2db/pkgstatistics_1.4.jar /home/santoku/Workspace/Proj201404/dot2smali/input/smali 3 10 google >pkgstatistics_googleplay.txt