#!/bin/bash

APKFILE=`cat ./.target`
echo $APKFILE
APKNAME=""
APKPATH=""

##step0
#todo: get the args
while getopts "f:" optname
  do
    case "$optname" in
      "f")
        echo "Option $optname has value $OPTARG" && APKFILE="${OPTARG}" && APKNAME=${APKFILE##*/} && APKNAME=${APKNAME%.*} && APKPATH=${APKFILE%/*}
        ;;
      "?")
        #echo "Unknown option $OPTARG"
        ;;
      ":")
        #echo "No argument value for option $OPTARG"
        ;;
      *)
      # Should not occur
        #echo "Unknown error while processing options"
        ;;
    esac
  done

java -jar ./getsignature/getsignature.jar ${APKFILE}

