#!/bin/bash

APKFILE="./shareIO/EDGExample.apk"
APKNAME="EDGExample"
APKPATH="./shareIO"
PKGNAME="fm.qingting.qtradio"
ACTNAME="fm.qingting.qtradio.QTRadioActivity"

##step0
#todo: get the args
while getopts ":af:n:p:" optname
  do
    case "$optname" in
      "a")
        echo "Option $optname is specified"
        ;;
      "f")
        echo "Option $optname has value $OPTARG" && APKFILE="${OPTARG}" && APKNAME=${APKFILE##*/} && APKNAME=${APKNAME%.*} && APKPATH=${APKFILE%/*}
        ;;
      "n")
        echo "Option $optname has value $OPTARG" && APKNAME="${OPTARG}"
        ;;
      "p")
        echo "Option $optname has value $OPTARG" && APKPATH="${OPTARG}"
        ;;
      "?")
        echo "Unknown option $OPTARG"
        ;;
      ":")
        echo "No argument value for option $OPTARG"
        ;;
      *)
      # Should not occur
        echo "Unknown error while processing options"
        ;;
    esac
  done

echo "apk-name: ${APKNAME}"
echo "apk-path: ${APKPATH}"

rm -rf ./dot2smali/input/dot/${APKNAME}
rm -rf ./dot2smali/input/smali/${APKNAME}
rm -rf ./dot2smali/output/dot/${APKNAME}
rm -rf ./dot2smali/output/smali/${APKNAME}

function __readINI()
{
  INIFILE=$1; SECTION=$2; ITEM=$3
  _readIni=`awk -F '=' '/\['$SECTION'\]/{a=1}a==1&&$1~/'$ITEM'/{print $2;exit}' $INIFILE`
  echo ${_readIni}
}

PKGNAME=( $( __readINI ${APKPATH}/${APKNAME}.ini BASE pkgname ) )
ACTNAME=( $( __readINI ${APKPATH}/${APKNAME}.ini BASE mainactivity ) )

adb uninstall ${PKGNAME}
